version: '2.1'

services:

  app-db:
    container_name: app-db
    build: ./app/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres # to be override
      - POSTGRES_PASSWORD=postgres # to be override
    healthcheck:
      test: exit 0

  log-parser:
    container_name: log-parser
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=app.config.DevelopmentConfig # to be override
      - DATABASE_URL=postgres://postgres:postgres@app-db:5432/app_dev # to be override
      - DATABASE_TEST_URL=postgres://postgres:postgres@app-db:5432/app_test
    depends_on:
      app-db:
        condition: service_healthy
    links:
      - app-db
