version: '2.1'

services:

  app-db:
    container_name: app-db
    build: ./app/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres # override on it prod!
      - POSTGRES_PASSWORD=postgres # override on it prod!
    healthcheck:
      test: exit 0

  log-parser:
    container_name: log-parser
    build: ./
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - SECRET_KEY=my_precious # override it on prod!
      - APP_SETTINGS=app.config.DevelopmentConfig # override it on prod!
      - DATABASE_URL=postgres://postgres:postgres@app-db:5432/app_dev # override it on prod!
      - DATABASE_TEST_URL=postgres://postgres:postgres@app-db:5432/app_test
    depends_on:
      app-db:
        condition: service_healthy
    links:
      - app-db
