"""empty message

Revision ID: 0940a8366cc2
Revises: d3d743888f7f
Create Date: 2017-11-09 22:59:57.304737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0940a8366cc2'
down_revision = 'd3d743888f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_address', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ip_address', 'country', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ip_address', type_='foreignkey')
    op.drop_column('ip_address', 'country_id')
    # ### end Alembic commands ###
