"""empty message

Revision ID: 0a0e0aaca1a0
Revises: e75844a2e54c
Create Date: 2017-11-10 01:19:54.827620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a0e0aaca1a0'
down_revision = 'e75844a2e54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_address', sa.Column('hits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ip_address', 'hits')
    # ### end Alembic commands ###
