"""empty message

Revision ID: 163a7339f310
Revises: 0a0e0aaca1a0
Create Date: 2017-11-10 08:29:33.172568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163a7339f310'
down_revision = '0a0e0aaca1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('is_rfi', sa.Boolean(), nullable=False))
    op.add_column('entry', sa.Column('is_sqli', sa.Boolean(), nullable=False))
    op.add_column('entry', sa.Column('is_web_shell', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'is_web_shell')
    op.drop_column('entry', 'is_sqli')
    op.drop_column('entry', 'is_rfi')
    # ### end Alembic commands ###
