"""empty message

Revision ID: 29de5647f867
Revises: 0940a8366cc2
Create Date: 2017-11-09 23:58:20.920727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29de5647f867'
down_revision = '0940a8366cc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('code', sa.String(length=2), nullable=False))
    op.create_unique_constraint(None, 'country', ['code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'code')
    # ### end Alembic commands ###
