"""empty message

Revision ID: 6d3fb7fd3f33
Revises: 45c792ef724b
Create Date: 2017-11-10 00:45:27.380027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3fb7fd3f33'
down_revision = '45c792ef724b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('country_name_key', 'country', type_='unique')
    op.drop_column('country', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.create_unique_constraint('country_name_key', 'country', ['name'])
    # ### end Alembic commands ###
