"""empty message

Revision ID: e75844a2e54c
Revises: ffccacd549e5
Create Date: 2017-11-10 01:14:40.763924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75844a2e54c'
down_revision = 'ffccacd549e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('country_code_key', 'country', type_='unique')
    op.add_column('ip_address', sa.Column('address', sa.String(length=32), nullable=False))
    op.drop_constraint('ip_address_ip_key', 'ip_address', type_='unique')
    op.create_unique_constraint(None, 'ip_address', ['address'])
    op.drop_column('ip_address', 'ip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ip_address', sa.Column('ip', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ip_address', type_='unique')
    op.create_unique_constraint('ip_address_ip_key', 'ip_address', ['ip'])
    op.drop_column('ip_address', 'address')
    op.create_unique_constraint('country_code_key', 'country', ['code'])
    # ### end Alembic commands ###
