"""empty message

Revision ID: ffccacd549e5
Revises: 6d3fb7fd3f33
Create Date: 2017-11-10 00:45:50.479356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffccacd549e5'
down_revision = '6d3fb7fd3f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('name', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'country', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'country', type_='unique')
    op.drop_column('country', 'name')
    # ### end Alembic commands ###
